1. Numpy Module
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

Why Use Numpy 

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

Data Science:
  It is a branch of computer science where we study how to store, use and analyze data for deriving information from it.

Why is Numpy Faster Than Lists

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

1.1 Numpy Getting Started

Install it using this command:

        pip install numpy
                or
        python -m pip install numpy

If this command fails, then use a python distribution that already has NumPy installed like, Anaconda, Spyder etc.

Import Numpy

    import numpy


In [3]:
import numpy as np    ## import numpy library as np (np is just short name for numpy library)  np can also called Alias
arr = np.array([10,20,30,40,50])   ## we can create a numpy array using np.array() function. Here we have created a 1D array with 5 elements.
print(arr)
print(type(arr))   ## we can check the type of the array using type() function. It will return <class 'numpy.ndarray'> which means it is a numpy array.

print("")
print("Check Version of np")
import numpy as np
print(np.__version__)

[10 20 30 40 50]
<class 'numpy.ndarray'>

Check Version of np
2.3.5


Attributes & data types

.shape — dimensions as a tuple  (No of rows and columns)

.ndim — number of dimensions

.dtype — element type

.astype() — cast to a new dtype

In [ ]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print("Original Array:")
print(a)
# Shape
print("\nShape of Array:")
print(a.shape) ## (2, 3)

# Number of Dimensions
print("\nNumber of Dimensions:")
print(a.ndim) ## 2

# Data Type
print("\nData Type:")
print(a.dtype)   # dtype('int64' or int32 both are same)

# Convert Data Type
b = a.astype(np.float32)
print("\nArray After Converting to float32:")
print(b)

print("\nNew Data Type:")
print(b.dtype)

Numpy Creating Arrays

In [7]:
import numpy as np
a = np.array([10, 20, 30, 40, 50])
print("Original Array:")
print(a)
print("")
## check type of array
print("Type of Array:")
print(type(a))

print("")
## Access one element 
print("Access 1st element:")
print(a[1])

print("")
## SLicing
print("Access elements from index 1 to 3:")
print(a[1:4])

print("")
## reverse Array
print("Reverse Array:")
print(a[::-1])

print("")
print("2D Array:")
## Create a 2D array
# 2D Array
import numpy as np
m = np.array([
    [1,2,3],   ## row 0
    [4,5,6]    ## row 1
])
print("Original 2D Array:")
print(m)

print("")
## Acess one 1 element
print("Access one element:")
print(m[1,2])  ## row 1 and column 2

print("")
## Acess one column
print("Access one column:")
print(m[:,1])

print("")
## 3D Array    in 3d array we divide array into matrix and each matrix is called as 2D array. So, 3D array is a collection of 2D arrays.
import numpy as np
arr = np.array([
    [                   ## Matrix 1
        [1,2,3],
        [4,5,6]
    ],
    [                 ## Matrix 2
        [7,8,9],
        [10,11,12]
    ]
])
print("Original 3D Array:")
print(arr)
print("")
print("Dimension of Array:")
print(arr.ndim)

print("")
print("Higher Dimension Array:")
## Higher Dimension Array
import numpy as np
arr = np.array([1,2,3,4], ndmin=5)
print("Original Array:")
print(arr)
print("")
print("Number of Dimensions:")
print(arr.ndim)

Original Array:
[10 20 30 40 50]

Type of Array:
<class 'numpy.ndarray'>

Access 1st element:
20

Access elements from index 1 to 3:
[20 30 40]

Reverse Array:
[50 40 30 20 10]

2D Array:
Original 2D Array:
[[1 2 3]
 [4 5 6]]

Access one element:
6

Access one column:
[2 5]

Original 3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Dimension of Array:
3

Higher Dimension Array:
Original Array:
[[[[[1 2 3 4]]]]]

Number of Dimensions:
5


NumPy Array Indexing

In [9]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print("Original Array:")
print(arr)
print("")
print("Access 0th index and 1st element:")
print(arr[0])
print("")
## Add 3rd and 4th element of array
print("2nd index element")
print(arr[2])
print("")
print("3rd index element")
print(arr[3])
print("")
print("Sum of 3rd and 4th elements:")
print(arr[2] + arr[3])

Original Array:
[1 2 3 4]

Access 0th index and 1st element:
1

2nd index element
3

3rd index element
4

Sum of 3rd and 4th elements:
7


Numpy Slicing

taking elements from one given index to another given index.

Synatax:
array[start:end]   From which index it is starting  and At which index it will stop but stop value will not beincluded
        or 
array[start:end:step] 

In [14]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print("Slicing Array:")
print(arr[1:5])

print("")
print("Slicing Array with start value only:")   
print(arr[4:])

print("")
print("Slicing Array with end value only:")   
print(arr[:4])

print("")
print("Slicing Array without start and end value:")
print(arr[:])

print("")
print("Slicing Array with negative index:")
print(arr[-3:-1])

Slicing Array:
[2 3 4 5]

Slicing Array with start value only:
[5 6 7]

Slicing Array with end value only:
[1 2 3 4]

Slicing Array without start and end value:
[1 2 3 4 5 6 7]

Slicing Array with negative index:
[5 6]


Numpy Datatype

In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
print("Original Array:")
print(arr)
print("")

print("Data Type of Array:")
print(arr.dtype)

print("")
## Define datatype
import numpy as np
arr=np.array([1,2,3,4],dtype="float")
print("Define datatype of array:")
print(arr)
print(arr.dtype)

print("")
## Define datatype
import numpy as np
arr=np.array([1,2,3],dtype="S")
print("Define String datatype of array:")
print(arr)
print(arr.dtype)

print("")
## astype() it transforms the data type of array into another data type. It is used to convert the data type of an array into another data type.
import numpy as np
arr = np.array([1.1, 2.2, 3.3])
print("Original Array:")
print(arr)
print("")
print("Array with converted data type:")
newarr=arr.astype(int)
print(newarr)
print("")
print("Data Type of New Array:")
print(newarr.dtype)

## Boolean Conversion
print("")
print("Boolean Conversion:")
import numpy as np
arr = np.array([1, 0, 3])   ## 0 is considered as False and any non-zero value is considered as True.
print("Original Array:")
print(arr)
print("")
print("Boolean Array:")
newarr=arr.astype(bool)
print(newarr)

Original Array:
[1 2 3 4]

Data Type of Array:
int64

Define datatype of array:
[1. 2. 3. 4.]
float64

Define String datatype of array:
[b'1' b'2' b'3']
|S1

Original Array:
[1.1 2.2 3.3]

Array with converted data type:
[1 2 3]

Data Type of New Array:
int64

Boolean Conversion:
Original Array:
[1 0 3]

Boolean Array:
[ True False  True]


Numpy Copy vs View

In [ ]:
## copy() method creates a new array that is a copy of the original array, and any changes made to the copy will not affect the original array. This is useful when you want to create a new array that is independent of the original array.
import numpy as np
arr=np.array([1,2,3,4]) ## original array should not be affected by changes made to the copy of the array. This is because the copy() method creates a new array that is a copy of the original array, and any changes made to the copy will not affect the original array.
copy_arr=arr.copy()
arr[0]=100
print("Original Array after changing first element:")
print(arr)
print("")
print("Copy of Original Array:")
print(copy_arr) 
## in this sceanrio original array changed but copy of original array is not changed because we have used copy() method to create a copy of original array. If we use view() method then both original and copy of original array will be changed because view() method creates a view of original array and any changes made to the view will affect the original array.

## view() method creates a view of the original array, which means that any changes made to the view will affect the original array. This is useful when you want to create a new array that is dependent on the original array.
import numpy as np
arr=np.array([1,2,3,4])
view_arr=arr.view()
arr[0]=100
print("Original Array after changing first element:")
print(arr)
print("")
print("View of Original Array:")
print(view_arr)
print("")
## base attribute returns the base object of the array. If the array owns its own data, then the base attribute will be None. If the array is a view of another array, then the base attribute will be a reference to the original array.
import numpy as np
arr=np.array([1,2,3])
x=arr.copy()
y=arr.view()
print(x.base)
print(" ")
print(y.base)

Original Array after changing first element:
[100   2   3   4]

Copy of Original Array:
[1 2 3 4]
Original Array after changing first element:
[100   2   3   4]

View of Original Array:
[100   2   3   4]
None
 
[1 2 3]


Numpy Shape it defines number of rows and columns in dimension

In [26]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("Original 2D Array Shape:")
print(arr.shape)

Original 2D Array Shape:
(2, 3)


Numpy Reshape it changes shape but data will remain same 

In [28]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print("Original 1D Array:")
print(arr)
print("")
print("Reshaping 1D Array to 2D Array:")
newarr=arr.reshape(2,3)
print(newarr)   ## total elements should be same in original and reshaped array. Here, original array has 6 elements and reshaped array also has 6 elements (2*3=6). If we try to reshape the array into a shape that does not have the same number of elements as the original array, we will get an error.

print("")
## Flattening array means converting a multi-dimensional array into a 1D array. We can use flatten() method to flatten the array. It returns a copy of the original array collapsed into one dimension.
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("Original 2D Array:")
print(arr)
flat=arr.reshape(-1)
print("Array after Flattening:")
print(flat)

Original 1D Array:
[1 2 3 4 5 6]

Reshaping 1D Array to 2D Array:
[[1 2 3]
 [4 5 6]]

Original 2D Array:
[[1 2 3]
 [4 5 6]]
Array after Flattening:
[1 2 3 4 5 6]


Numpy Iterating

In [32]:
## 1D Array
import numpy as np
arr=np.array([10,20,30])
print("iterating through 1D array: ")
for x in arr:
    print(x)
    
print("")
## 2D Array
print("iterating through 2D array: ")
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)
    
print("")
## nditer() Array   it is shortcut for n-dimensional iterator. It is used to iterate through an n-dimensional array. It is more efficient than using nested for loops to iterate through an n-dimensional array.
print("iterating through nditer array: ")
import numpy as np
arr=np.array([[1,2],[3,4]])
for x in np.nditer(arr):
    print(x)
    
print("")
## ndenumerate() Array   it is shortcut for n-dimensional enumerator. It is used to iterate through an n-dimensional array and return the index and value of each element in the array. It is more efficient than using nested for loops to iterate through an n-dimensional array.
print("iterating through ndenumerate array: ")
import numpy as np
arr=np.array([[10,20],[30,40]])
for index,value in np.ndenumerate(arr):
    print(index,value)

iterating through 1D array: 
10
20
30

iterating through 2D array: 
[1 2 3]
[4 5 6]

iterating through nditer array: 
1
2
3
4

iterating through ndenumerate array: 
(0, 0) 10
(0, 1) 20
(1, 0) 30
(1, 1) 40


Joining Array Combine 2 or more arrays

In [40]:
## concatenate() method is used to join two or more arrays along an existing axis. It takes a sequence of arrays as input and returns a new array that is the concatenation of the input arrays. The axis parameter specifies the axis along which the arrays will be joined. If axis=0, the arrays will be joined vertically (row-wise), and if axis=1, they will be joined horizontally (column-wise).
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print("Concatenated Array:")
print(arr)

print("")
## 2D Array Concatenation
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6]])
arr = np.concatenate((arr1,arr2),axis=0)
print("Concatenated 2D Array:")
print(arr)

print("")
## Stack() method is used to join two or more arrays along a new axis. It takes a sequence of arrays as input and returns a new array that is the concatenation of the input arrays along a new axis. The axis parameter specifies the axis along which the arrays will be joined. If axis=0, the arrays will be joined vertically (row-wise), and if axis=1, they will be joined horizontally (column-wise).
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2))
print("Stacked Array:")
print(arr)

print("")
## hstack() method is used to join two or more arrays horizontally (column-wise). It takes a sequence of arrays as input and returns a new array that is the concatenation of the input arrays along the second axis (axis=1).
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Horizontally Stacked Array:")
print(np.hstack((a,b)))

print("")
## vstack() method is used to join two or more arrays vertically (row-wise). It takes a sequence of arrays as input and returns a new array that is the concatenation of the input arrays along the first axis (axis=0).
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Vertically Stacked Array")
print(np.vstack((a,b)))

print("")
## dstack() depth stack it creates third dimension
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Depth STacked Array")
print(np.dstack((a,b)))


Concatenated Array:
[1 2 3 4 5 6]

Concatenated 2D Array:
[[1 2]
 [3 4]
 [5 6]]

Stacked Array:
[[1 2 3]
 [4 5 6]]

Horizontally Stacked Array:
[1 2 3 4 5 6]

Vertically Stacked Array
[[1 2 3]
 [4 5 6]]

Depth STacked Array
[[[1 4]
  [2 5]
  [3 6]]]


Splitting Array

In [44]:
## array_split()
import numpy as np
arr=np.array([1,2,3,4,5,6])
new=np.array_split(arr,3)
print("Split an array")
print(new)

print("")
## Unequal Split()
import numpy as np
arr=np.array([1,2,3,4,5,6])
new=np.array_split(arr,4)
print("Unequal Split Array")
print(new)

print("")
## Split 2D Array
import numpy as np
arr=np.array([[1,2],
              [3,4],
              [5,6],
              [7,8]])

new=np.array_split(arr,2)
print(new)

print("")
## Split by columns
import numpy as np
arr=np.array([[1,2,3],
              [4,5,6]])
new=np.array_split(arr,3,axis=1)
print("Split an array by columns")
print(new)

Split an array
[array([1, 2]), array([3, 4]), array([5, 6])]

Unequal Split Array
[array([1, 2]), array([3, 4]), array([5]), array([6])]

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]

Split an array by columns
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


Numpy Sort Array

In [48]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print("Original Array:")
print(arr)

print("\nSorted Array:")
print(np.sort(arr))

print("")
## Sort string
import numpy as np
arr = np.array(["banana","cherry","apple"])
print("Sort String")
print(np.sort(arr))

print("")
## Sort 2D array
import numpy as np
arr=np.array([[3,2,4],
              [5,0,1]])
print("Sort 2D Array")
print(np.sort(arr))

Original Array:
[3 2 0 1]

Sorted Array:
[0 1 2 3]

Sort String
['apple' 'banana' 'cherry']

Sort 2D Array
[[2 3 4]
 [0 1 5]]


Numpy Filter Array

In [52]:
## Boolean Indexing
import numpy as np
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print("Boolean Filtering")
print(newarr)

print("")
print("Manual Filtering")
## Manual Filtering
import numpy as np
arr=np.array([41,42,43,44])
filter_arr=[]
for element in arr:
    if element>42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
print(filter_arr)
newarr=arr[filter_arr]
print("New Array")
print(newarr)

print("")
print("Even Number Filtering")
## Even Number
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
filter_arr=arr%2==0
print(filter_arr)
newarr=arr[filter_arr]
print("New Array")
print(newarr)

Boolean Filtering
[41 43]

Manual Filtering
[False, False, True, True]
New Array
[43 44]

Even Number Filtering
[False  True False  True False  True False]
New Array
[2 4 6]
