1. Random Number

Random number does NOT mean a different number every time. Random means something that can not be predicted logically.
Each time output will be different

True Random vs Pseudo Random

True Random
* Completely unpredictable.
* Comes from a source outside the computer.
* **Examples:**

  * Mouse movement
  * Keyboard typing
  * Network timing
* Mostly used for security, such as encryption.

Pseudo Random

* Generated by a computer algorithm.
* It is not truly random, but it appears random to us.
* NumPy uses pseudo-random numbers.



In [1]:
## Import Random Module

from numpy import random

## random.randint()  it generate random integer
x = random.randint(100)
print(x)

print("")
## range
print("Show Range")
random.randint(50,100)
print(x)

## random.rand()    generate float 
print("")
print("show decimal random")
from numpy import random
x=random.rand()
print(x)

## random Array 
print("")
print("Show Random Array")
x=random.randint(100,size=(5))
print(x)
## 2D Array
print("")
print("show 2D Array")
x=random.randint(100,size=(3,5))
print(x)

## Random Flat Array
print("")
print("Random Float ")
x=random.rand(5)
print(x)

## random.choice()
print("")
print("Random Choice")
x=random.choice([3,5,7,9])
print(x)

81

Show Range
81

show decimal random
0.47440297262123854

Show Random Array
[83 64 98 48 20]

show 2D Array
[[84 48 11 81 46]
 [ 7 63 80  3 42]
 [73 82 75 83 39]]

Random Float 
[0.84706558 0.27968077 0.29992993 0.68485791 0.79113632]

Random Choice
5


2. Random Data Distribution

Probability of incoming Values

In [4]:
from numpy import random
x=random.choice([3,5,7,9],
p=[0.1,0.3,0.6,0.0],   ## sum of probability should be 1 
size=(100)
)
print(x)

[5 7 3 7 7 7 7 7 5 7 5 7 5 7 7 5 5 5 7 5 7 5 7 7 7 7 7 5 5 7 5 5 7 7 7 5 7
 5 5 7 5 5 7 7 5 7 7 5 7 7 7 5 7 3 7 5 7 7 7 3 7 7 7 7 3 5 7 5 7 5 7 3 3 7
 5 7 5 5 7 7 7 5 7 5 5 7 7 7 7 5 7 7 7 7 5 7 7 5 7 5]


3. Random Permutation

Change Arrangements

In [3]:
## Shuffle()               change the original Array
from numpy import random
import numpy as np
arr=np.array([1,2,3,4,5])
random.shuffle(arr)
print("Shuffle() Method")
print(arr)

## Permutation() Method     original array remains same
print("")
print("Permutation() Method")  
arr=np.array([1,2,3,4,5])
x=random.permutation(arr)
print(x)
print(arr)


Shuffle() Method
[1 4 3 2 5]

Permutation() Method
[2 5 4 1 3]
[1 2 3 4 5]
