# NumPy ufuncs (Universal Functions)

What are ufuncs?

ufunc stands for Universal Function.

These are built-in NumPy functions that work directly on NumPy arrays (ndarray)

Instead of processing one element at a time using loops, ufuncs process the entire array at once

## Why use ufuncs?

ufuncs are much faster than Python loops because they use vectorization

# Advantages:

- Faster execution
- Less code
- Works directly with arrays
- Supports broadcasting

# Supports methods like reduce(), accumulate()

## Vectorization

Vectorization means performing an operation on the entire array at once instead of using loops

In [1]:
## With out Vectprization

x = [1,2,3,4,5]
y = [2,3,789,0,1]

z = []

for i,j in zip(x,y):
    z.append(i+j)

print(z)

## Python adds elements one by one using a loop

[3, 5, 792, 4, 6]


WIth Vactorization(Ufunc)

In [ ]:
import numpy as np
x = [1,2,3,4,5]
y = [2,3,789,0,1]
z = np.add(x,y)
print(z)

# No loop is required
# NumPy automatically adds every corresponding element


## Create Your Own Ufunc

Normally NumPy provides many ufuncs

You can also create your own


In [3]:
## Step 1: Create a normal function

def myadd(x,y):
    return x+y

## Step 2: Convert it into ufunc

# Syntax -> np.frompyfunc(function, inputs, outputs)
## function	-> Function name
## inputs ->  Number of input arguments
## outputs -> Number of output values

import numpy as np

myadd = np.frompyfunc(myadd,2,1)

In [2]:
## Example

import numpy as np

def myadd(x,y):
    return x+y

myadd = np.frompyfunc(myadd,2,1)

print(myadd([1,2,3],[12,3,4]))

[13 5 7]


Check if a Function is a ufunc

In [4]:
# Check if a Function is a ufunc

import numpy as np
print(type(np.add))

# <class 'numpy.ufunc'> -> It means add() is a ufunc

<class 'numpy.ufunc'>


In [5]:
## Example

print(type(np.concatenate))

# concatenate() is not a ufunc

<class 'numpy._ArrayFunctionDispatcher'>


Using if Statement

In [6]:
## Using if Statement

import numpy as np
if type(np.add) == np.ufunc:
    print("add is ufunc")
else:
    print("add is not ufunc")

add is ufunc


## Simple Arithmeticc ufuncs

## These functions perform arithmetic on two arrays element by element

1. add

In [ ]:
#  Adds corresponding elements

import numpy as np

array1 = np.array([1,2,3,45,5])
array2 = np.array([1,2,32,78,9])

print(np.add(array1,array2))

[  2   4  35 123  14]


2.subtract()

In [9]:
## Subtracts second array from first array

import numpy as np

array1 = np.array([1,3,3,45,5])
array2 = np.array([1,2,32,78,9])

print(np.subtract(array1,array2))


[  0   1 -29 -33  -4]


3. multiply()

In [ ]:
## Multiplies corresponding elements

import numpy as np

array1 = np.array([1,6,3,45,5])
array2 = np.array([1,2,32,78,9])

print(np.multiply(array1,array2))


[   1    4   96 3510   45]


4. divide()

In [12]:
## Divides first array by second array

import numpy as np

array1 = np.array([1,6,32,45,5])
array2 = np.array([1,2,2,78,9])

print(np.divide(array1,array2))

[ 1.          3.         16.          0.57692308  0.55555556]


5. power()

In [13]:
## Raises first array values to the power of second array values

import numpy as np

array1 = np.array([1,2,3,5,5])
array2 = np.array([1,2,2,8,9])

print(np.power(array1,array2))


[      1       4       9  390625 1953125]


6. mod()/ remainder()

In [14]:
## Returns the remainder after division

import numpy as np

array1 = np.array([1,12,2,78,9])
array2 = np.array([1,2,32,45,5])

print(np.mod(array1,array2))

print(np.remainder(array1,array2))

## np.mod() and np.remainder() produce the same result


[ 0  0  2 33  4]
[ 0  0  2 33  4]


7. divmod()

In [15]:
## Returns both quotient and remainder

import numpy as np

array1 = np.array([10,20,30])
array2 = np.array([3,7,9])

print(np.divmod(array1,array2))

#In Output:
# First array -> Quotient
# Second Array -> Remainder

(array([3, 2, 3]), array([1, 6, 3]))


8. absolute()

In [16]:
## Converts negative numbers into positive numbers

arr = np.array([1,-2,33,-56,-9,-32])

print(np.absolute(arr))

# Absolute value simply removes the negative sign

[ 1  2 33 56  9 32]


Numpy Rounding Functions

Numpy provides  different ways to round decimal numbers 

trunc()

In [17]:
## trunc()

# Removes the decimal part

array = np.array([32.34, 45.91,-23.0])

print(np.trunc(array))

# It simply cuts off the decimal part


[ 32.  45. -23.]


fix()

In [18]:
## fix()

# Works exactly like trunc()

arr = np.array([23.34, -45.91,23.0])

print(np.fix(arr))

[ 23. -45.  23.]


around()

In [ ]:
## Rounds to a specified number of decimal places

# (number, round decimal place number)
print(np.around(3.1116,2))
print(np.around(3.1116,3))
print(np.around(3.1386,2))

3.11
3.112
3.14


floor()

In [20]:
# Rounds down to the nearest integer

print(np.floor([3.1, 4.9, -3.6, -5.1]))

# Floor always moves downward

[ 3.  4. -4. -6.]


ceil()

In [21]:
# Rounds up to the nearest integer

print(np.ceil([3.1,  4.9, -3.6, -5.1]))

# Ceil always moves upward

[ 4.  5. -3. -5.]


ufunc Numpy Logs

In [22]:
# A logarithm answers the question:

# "To what power should the base be raised to get the given number?

## Example
# 2³ = 8
# So
# log₂(8)=3

log2()

In [24]:
# Calculates logarithm with base 2

import numpy as np 
array = np.arange(2,10)
print(np.log2(array))

# log₂(1)=0

# log₂(2)=1

# log₂(4)=2

# log₂(8)=3


[1.         1.5849625  2.         2.32192809 2.5849625  2.80735492
 3.         3.169925  ]
