## 1.Numpy Summation 

What is difference between summation and Addition?

Addition add two values and summation is in between multiple values 

Mathematics Notation: ∑

In [ ]:
## Example 
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
newarr = np.add(arr1, arr2)
print("Addition")
print(newarr)

print("")
print("Sum")
## Example 
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
newarr = np.sum([arr1, arr2])
print(newarr)

print("")
print("Sum with vertices ")
## Example 
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
newarr = np.sum([arr1, arr2],axis=1)
print(newarr)
## axis=0 = vertically (columns)
## axis=1 = horizontally (rows)


## Cummulative sum (cumsum)
print("")
print("Cumulative Sum")
import numpy as np
arr=np.array([1,2,3])
newarr=np.cumsum(arr)
print(newarr)

Addition
[2 4 6]

Sum
12

Sum with vertices 
[6 6]

Cumulative Sum
[1 3 6]


## 2. NUMPY Production 

Multiply Numbers 

In [ ]:
## Example 1
import numpy as np
arr = np.array([1,2,3,4])
x = np.prod(arr)
print("Product of single array")
print(x)

print("")
## Example 2 
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
x = np.prod([arr1,arr2])
print("Product of two arrays")
print(x)

print("")
## Product over axis       it gives row by row answer
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
newarr=np.prod([arr1,arr2],axis=1)
print("Production over axis")
print(newarr)

print("")
## Cumulative Product   it save product of each state and each state answer multiplies with next value
import numpy as np
arr=np.array([5,6,7,8])
newarr=np.cumprod(arr)
print("Cumulative Product")
print(newarr)


Product of single array
24

Product of two arrays
40320

Production over axis
[  24 1680]

Cumulative Product
[   5   30  210 1680]


## 3.NUMPY Difference

Calculate Difference of two consecutive values 

Next Element - Previous Element

or 

Current Value - Previous Value

In [21]:
import numpy as np
arr = np.array([10, 15, 25, 5])   ## when next value is small then we have negative value in return
newarr = np.diff(arr)
print("Difference of an array")
print(newarr)

print("")
import numpy as np
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr, n=2)
print("Differnec Opernation twice")
print(newarr)

Difference of an array
[  5  10 -20]

Differnec Opernation twice
[  5 -30]


## 4.NumPy LCM Lowest Common Multiple

The Lowest Common Multiple is the smallest number that is a common multiple of two numbers.

In [20]:
import numpy as np
num1 = 4
num2 = 6
x = np.lcm(num1, num2)
print("LCM")
print(x)

print("")
## LCM of Array 
import numpy as np
arr = np.array([3, 6, 9])
x = np.lcm.reduce(arr)   ## reduce() apply same function on each element of array repeadtely 
print("LCM of array")
print(x)

print("")
## Arrange 
import numpy as np
arr = np.arange(1,11)   ## arrange indictes start and stop value
x=np.lcm.reduce(arr)
print("LCM")
print(x)

LCM
12

LCM of array
18

LCM
2520


## 5.NumPy GCD Greatest Common Divisor

The GCD (Greatest Common Divisor), also known as HCF (Highest Common Factor) is the biggest number that is a common factor of both of the numbers.

In [19]:
import numpy as np
num1 = 6
num2 = 9
x = np.gcd(num1, num2)
print("GCD")
print(x)

print("")
print("GCD in Array")
import numpy as np
arr = np.array([20, 8, 32, 36, 16])
x = np.gcd.reduce(arr)
print(x)

GCD
3

GCD in Array
4


## 6.NUMPY TRIGNOMETRIC FUNCTIONS

NumPy provides the ufuncs sin(), cos() and tan() that take values in radians and produce the corresponding sin, cos and tan values.

In [26]:
import numpy as np
x = np.sin(np.pi/2)
print("The Sine value of pI/2")
print(x)

## Find sine values for all of the values in arr:
print("")
import numpy as np
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.sin(arr)
print("Sine values for all of the values in arr:")
print(x)

## Convert Degrees Into Radians
print("")
import numpy as np
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
print("Convert Degrees Into Radians")
print(x)

##Radians to Degrees
print("")
import numpy as np
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
x = np.rad2deg(arr)
print("Convert Radians to Degrees")
print(x)

## Finding Angles 
print("")
## arcsin()
import numpy as np
x = np.arcsin(1.0)
print("Finding Angle using arcsin()")
print(x)

print("")
import numpy as np
arr = np.array([1, -1, 0.1])
x = np.arcsin(arr)
print("Finding Angle of each value using arcsin()")
print(x)

## Hypotenues
##  takes the base and perpendicular values and produces hypotenues based on pythagoras theorem.
import numpy as np
base = 3
perp = 4
x = np.hypot(base, perp)
print("Hypotenues for base 4 and perpendicular 3")
print(x)



The Sine value of pI/2
1.0

Sine values for all of the values in arr:
[1.         0.8660254  0.70710678 0.58778525]

Convert Degrees Into Radians
[1.57079633 3.14159265 4.71238898 6.28318531]

Convert Radians to Degrees
[ 90. 180. 270. 360.]

Finding Angle using arcsin()
1.5707963267948966

Finding Angle of each value using arcsin()
[ 1.57079633 -1.57079633  0.10016742]
Hypotenues for base 4 and perpendicular 3
5.0


## 7. NUMPY Hyperbolic Functions 

NumPy provides the ufuncs sinh(), cosh() and tanh() that take values in radians and produce the corresponding sinh, cosh and tanh values

In [29]:
import numpy as np
x = np.sinh(np.pi/2)
print("Sinh")
print(x)

print("")
import numpy as np
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.cosh(arr)
print("cosh values for all of the values in arr:")
print(x)

## Finding Angles 
print("")
## Numpy provides ufuncs arcsinh(), arccosh() and arctanh() that produce radian values for corresponding sinh, cosh and tanh values given.
import numpy as np
x = np.arcsinh(1.0)
print("The angle of 1.0 using arcsinh:")
print(x)

print("")
##  Angles of Each Value in Arrays
import numpy as np
arr = np.array([0.1, 0.2, 0.5])
x = np.arctanh(arr)
print("Angles of Each Value in Arrays")
print(x)

Sinh
2.3012989023072947

cosh values for all of the values in arr:
[2.50917848 1.60028686 1.32460909 1.20397209]

The angle of 1.0 using arcsinh:
0.881373587019543

Angles of Each Value in Arrays
[0.10033535 0.20273255 0.54930614]


## 8.NUMPY Set Operations 

What is set 

A set in mathematics is a collection of unique elements.

Sets are used for operations involving frequent intersection, union and difference operations.

In [ ]:
import numpy as np
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr)
print("Create Unique set")
print(x)


## Finding Union   To find the unique values of two arrays
print("")
print("Finding Union")
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.union1d(arr1, arr2)
print(newarr)

Create Unique set
[1 2 3 4 5 6 7]

Finding Union
[1 2 3 4 5 6]


In [ ]:
## Findng  Intersection
## To find only the values that are present in both arrays
print("")
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.intersect1d(arr1, arr2, assume_unique=True)
print("Intersection of two arrays")
print(newarr)

## Finding DIfference 
print("")
import numpy as np
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])
newarr = np.setdiff1d(set1, set2, assume_unique=True)
print("The difference of the set1 from set2:")
print(newarr)

## Finding Symmetric Difference
## To find only the values that are NOT present in BOTH sets
print("")
import numpy as np
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])
newarr = np.setxor1d(set1, set2, assume_unique=True)
print("Symmetric Difference of two sets")
print(newarr)


Intersection of two arrays
[3 4]

The difference of the set1 from set2:
[1 2]
