numpy(NUmerical Python)    fast calculations with numbers 
np.array — wraps a list/tuple
np.zeros — pre-filled placeholder
np.arange — like range(), returns an array
np.linspace — n evenly spaced points

In [4]:
import numpy as np  ## import library 

a = np.array([1,2,3])  ## convert python list into numpy array
b = np.array([4,5,6])

print(a+b)   ## in list they will be concatenated [1,2,3,4,5,6] but in numpy array they will be added element wise [5,7,9]

[5 7 9]


Attributes & data types
.shape — dimensions as a tuple  (No of rows and columns)
.ndim — number of dimensions
.dtype — element type
.astype() — cast to a new dtype


In [ ]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print("Original Array:")
print(a)
# Shape
print("\nShape of Array:")
print(a.shape) ## (2, 3)

# Number of Dimensions
print("\nNumber of Dimensions:")
print(a.ndim) ## 2

# Data Type
print("\nData Type:")
print(a.dtype)   # dtype('int64' or int32 both are same)

# Convert Data Type
b = a.astype(np.float32)
print("\nArray After Converting to float32:")
print(b)

print("\nNew Data Type:")
print(b.dtype)


Original Array:
[[1 2 3]
 [4 5 6]]

Shape of Array:
(2, 3)

Number of Dimensions:
2

Data Type:
int64

Array After Converting to float32:
[[1. 2. 3.]
 [4. 5. 6.]]

New Data Type:
float32


Indexing and slicing 

In [2]:
import numpy as np
a = np.array([10, 20, 30, 40, 50])
print(a)
## Access one element 
print(a[1])

## SLicing
print(a[1:4])

## reverse Array
print(a[::-1])

[10 20 30 40 50]
20
[20 30 40]
[50 40 30 20 10]


In [3]:
## 2D Array
import numpy as np
m = np.array([
    [1,2,3],   ## row 0
    [4,5,6]    ## row 1
])
print(m)

## Acess one 1 element
print(m[1,2])  ## row 1 and column 2

## Acess one column
print(m[:,1])


[[1 2 3]
 [4 5 6]]
6
[2 5]


Boolean and Fancy Indexing

In [ ]:
import numpy as np

# Create NumPy array
a = np.array([4, 7, 2, 9, 1, 8])

print("Original Array:")
print(a)

# Boolean Masking
mask = a > 5

print("\nBoolean Mask:")
print(mask)

print("\nValues greater than 5:")
print(a[mask])   ## pick only true values from mask

# Replace values greater than 5
a[a > 5] = 0

print("\nArray after replacing values > 5 with 0:")
print(a)

# Fancy Indexing

idx = [0, 2, 4]
print("\nSelected positions:")
print(idx)

print("Values at these positions:")
print(a[idx])